### PR TITLE
Final Updates for R4

### PR DESCRIPTION
**Pull request by amsmith-pro**

### CODE REVIEW

**Comment by amsmith-pro** [comment]
In `local-dev/docker-compose/aetheric-svc.yml` the list of environment variables have a `<SERVICE>_PORT_REST` for each service with a REST server. However this variable is never used since the docker-compose.yml exposes the respective REST ports per service via `ports:` using the `<SERVICE>_HOST_PORT_REST` variable in the dotfile.

I assume then that `<SERVICE>_PORT_REST` is simply an empty string that isn't read by the program

**Comment by amsmith-pro** [comment]
Add a (commented) dozzle instance in the docker-compose.yaml for easier log perusal, extended timeouts for health checks otherwise certain services (like svc-storage and svc-gis) don't have long enough to start.

One slightly misleading log warning for multiple services is this:
image

Which is only because "Config::try_from_env" is being used, and in some instances it starts with creating a default:
image

**Comment by owlot** [comment]
> In `local-dev/docker-compose/aetheric-svc.yml` the list of environment variables have a `<SERVICE>_PORT_REST` for each service with a REST server. However this variable is never used since the docker-compose.yml exposes the respective REST ports per service via `ports:` using the `<SERVICE>_HOST_PORT_REST` variable in the dotfile.
> 
> I assume then that `<SERVICE>_PORT_REST` is simply an empty string that isn't read by the program

I've done some testing and the `environment` configuration is indeed mostly redundant due to the already present `.env` file.
It can be replaced with this configuration:
```
    environment:
      - ASSETS_PORT_GRPC=${DOCKER_PORT_GRPC}
      - ATC_PORT_GRPC=${DOCKER_PORT_GRPC}
      - CARGO_PORT_GRPC=${DOCKER_PORT_GRPC}
      - COMPLIANCE_PORT_GRPC=${DOCKER_PORT_GRPC}
      - CONTACT_PORT_GRPC=${DOCKER_PORT_GRPC}
      - DISCOVERY_PORT_GRPC=${DOCKER_PORT_GRPC}
      - GIS_PORT_GRPC=${DOCKER_PORT_GRPC}
      - PRICING_PORT_GRPC=${DOCKER_PORT_GRPC}
      - SCHEDULER_PORT_GRPC=${DOCKER_PORT_GRPC}
      - STORAGE_PORT_GRPC=${DOCKER_PORT_GRPC}
      - TELEMETRY_PORT_GRPC=${DOCKER_PORT_GRPC}
```

**Comment by amsmith-pro** [comment]
<details>

> > In `local-dev/docker-compose/aetheric-svc.yml` the list of environment variables have a `<SERVICE>_PORT_REST` for each service with a REST server. However this variable is never used since the docker-compose.yml exposes the respective REST ports per service via `ports:` using the `<SERVICE>_HOST_PORT_REST` variable in the dotfile.
> > I assume then that `<SERVICE>_PORT_REST` is simply an empty string that isn't read by the program
> 
> I've done some testing and the `environment` configuration is indeed mostly redundant due to the already present `.env` file. It can be replaced with this configuration:
> 
> ```
>     environment:
>       - ASSETS_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - ATC_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - CARGO_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - COMPLIANCE_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - CONTACT_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - DISCOVERY_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - GIS_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - PRICING_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - SCHEDULER_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - STORAGE_PORT_GRPC=${DOCKER_PORT_GRPC}
>       - TELEMETRY_PORT_GRPC=${DOCKER_PORT_GRPC}
> ```

</details>

https://github.com/Arrow-air/tools/pull/53/commits/706d5b0ae9720958a637cd3343f76060b58acd7b

**Review by owlot — APPROVED** [review]

**Pull request merged**
